name: Continuous delivery

# Running on the `main` branch
on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  continuous_integration:
    uses: ./.github/workflows/continuous_integration.yml
  continuous_delivery:
    runs-on: ubuntu-22.04
    needs:
      - continuous_integration # The continuous integration must succeed before the continuous delivery starts

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup wrapper for flyctl # https://github.com/superfly/flyctl-actions
        uses: superfly/flyctl-actions/setup-flyctl@dfdfedc86b296f5e5384f755a18bf400409a15d0
        with:
          version: 0.0.451 # See versions at https://github.com/superfly/flyctl

      - name: Deploy to https://fly.io/
        # `--remote-only` - Perform builds on a remote builder instance instead of using the local docker daemon
        run: flyctl deploy --remote-only
